GST=		gst
GST_SUNIT=	gst-sunit


run: day03.st
	${GST} -f day03.st input

run-example: day03.st
	${GST} -f day03.st example

runb: day03b.st
	${GST} -f day03b.st input

runb-example: day03b.st
	${GST} -f day03b.st example

